version: 0.0
os: linux

files:
  - source: scripts/sb-sample-app.service
    destination: /lib/systemd/system/
  - source: target/sample-app-0.0.1-SNAPSHOT.jar
    destination: /app

hooks:
  Install:
    - location: ./install.sh
  AfterInstall:
    - location: ./xd.sh