version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install -y maven default-jdk
  build:
    commands: 
    - mvn install
artifacts:
  files:
    - target/sample-app-0.0.1-SNAPSHOT.jar