version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install wget -y
      - wget https://apache.osuosl.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
      - tar -xvf apache-maven-3.6.3-bin.tar.gz
      - mv apache-maven-3.6.3/bin/* /usr/bin
      - yum install -y default-jdk
  build:
    commands: 
    - mvn install
artifacts:
  files:
    - target/sample-app-0.0.1-SNAPSHOT.jar