version: 0.2

phases:
  install:
    commands:
      - rm -rf /etc/apt/sources.list.d/*
      - apt update -y
      - apt install maven default-jdk -y
  build:
    commands: 
    - mvn install
artifacts:
  files:
    - target/sample-app-0.0.1-SNAPSHOT.war
    - appspec.yml