version: 0.2

phases:
  install:
    commands:
      - yum update -y
      - yum install wget -y
      - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
      - yum install -y apache-maven default-jdk
  build:
    commands: 
    - mvn install
artifacts:
  files:
    - target/sample-app-0.0.1-SNAPSHOT.jar