version: 0.2

phases:
  install:
    commands:
      - sudo apt update -y
      - sudo apt install -y maven default-jdk
  build:
    command: mvn install
artifacts:
  files:
    - target/sample-app-0.0.1-SNAPSHOT.jar